@startuml
hide empty description

[*] -[#blue]-> Open

Open -[#blue]-> In_Progress
In_Progress -[#blue]-> Resolved
In_Progress -[#red]-> Open

Resolved -[#blue]-> Closed
Resolved -[#red]-> Open : Reopen

Closed -[#blue]-> [*]
@enduml