@startuml
hide empty description
[*] -[#blue]-> OPEN

OPEN -[#blue]-> IN_PROGRESS
IN_PROGRESS -[#blue]-> RESOLVED
IN_PROGRESS -[#red]-> OPEN

RESOLVED -[#blue]-> CLOSED
RESOLVED -[#red]-> OPEN

CLOSED -[#blue]-> [*]
CLOSED -[#red]-> OPEN
@enduml