@startuml
hide empty description
[*] -[#blue]-> OPEN
OPEN: Primary task status
OPEN -[#blue]-> IN_PROGRESS

IN_PROGRESS: Working on the task
IN_PROGRESS -[#blue]-> RELEASED_TO_TEST
IN_PROGRESS -[#red]-> OPEN
IN_PROGRESS --> BLOCKED

BLOCKED --> OPEN

RELEASED_TO_TEST -[#blue]-> RELEASED_TO_PRODUCTION

RELEASED_TO_PRODUCTION -[#blue]-> [*]
@enduml